# Generated by Django 6.1.1 on 2026-09-16 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('summary', models.TextField(help_text='One or two sentences describing the project.')),
                ('location', models.CharField(max_length=150)),
                ('responsible_organization', models.CharField(max_length=200)),
                ('official_status', models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing'), ('planned', 'Planned'), ('stalled', 'Stalled')], max_length=20)),
                ('official_status_date', models.DateField(help_text='Date the official status was recorded or announced.')),
                ('source_name', models.CharField(help_text='Where the official claim came from, e.g. a ministry report or county gazette notice.', max_length=200)),
                ('source_url', models.URLField(blank=True)),
                ('is_demo_data', models.BooleanField(default=True, help_text='Marks records seeded for demonstration rather than sourced from a real institution.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_observed', models.DateField()),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('not_operational', 'Not operational'), ('in_progress', 'In progress'), ('no_activity', 'No activity observed'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(help_text="What was observed, in the reporter's own words.")),
                ('evidence_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('document', 'Document'), ('testimony', 'Testimony / eyewitness account')], max_length=20)),
                ('evidence_note', models.CharField(blank=True, help_text='A short note on the evidence, e.g. a photo caption or where a document can be found.', max_length=255)),
                ('submitted_by', models.CharField(blank=True, default='Anonymous', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='evidence.project')),
            ],
            options={
                'ordering': ['-date_observed', '-created_at'],
            },
        ),
    ]
